### ISSUE TITLE
Flickering issue in iOS

### ISSUE THREAD

**Issue by Jacqueline94-Koo** [gabriel-x-duarte/basic_loading_overlay#1]
Recently after updated to flutter 3.17.3, I found out that when the loading is first use in a page, it cause the flickering issue happen, however after that, there is no flickering happen. Maybe can help check what cause this happen? It only happen is iOS 

https://github.com/gabriel-x-duarte/basic_loading_overlay/assets/62096300/542b01fa-3c3e-4564-9d05-d9aaa2897bf0

**Comment by gabriel-x-duarte** [comment]
Hello Jacqueline! Thanks for reaching me!
This bug is quite weird. I haven’t seen this issue on my apps. I just ran an application on my mac M1 to try out and see if this bug happens with me, but it doesn’t . Do you know if when this bug happens, in the terminal, does it print any error? And if it do print errors, can you please share this information as well?

But I have a suggestion that might help you. First thing is that you mentioned that the version of flutter you are using is 3.17.3, but the latest stable release is 3.16.2, which is the version that I used to try to catch the error that you showed. I could not catch this bug in my application. So you might be using a Beta version of Flutter. This is actually not good for apps in production, because this versions are not well tested. So the suggestion that I give you is to change your flutter channel to Stable. I think this can solve the problem. If you cannot change to Stable version, another suggestion that I give you, is to try to give a little delay before calling LoadingOverlay.show() with Future.delayed(Duration(milliseconds: 150)). but I don’t think this will help, because I dont think this is the issue. I believe that this version 3.17.3 might have some problem.

Here you can see the flutter versions:
https://docs.flutter.dev/release/archive

Please let me know if you could fix this issue, and if there are any logs of errors in the terminal, please share with me.

Have a good day!

**Comment by Jacqueline94-Koo** [comment]
Hi, I think is my side made a mistake. Thanks for reply.
